-- MySQL Script generated by MySQL Workbench
-- Thu May 20 18:58:40 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema project
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `project` ;

-- -----------------------------------------------------
-- Schema project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `project` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `project` ;

-- -----------------------------------------------------
-- Table `project`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`users` ;

CREATE TABLE IF NOT EXISTS `project`.`users` (
  `users_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`users_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `users_id` (`users_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `project`.`hotels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`hotels` ;

CREATE TABLE IF NOT EXISTS `project`.`hotels` (
  `hotels_id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `prefecture` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `rooms` VARCHAR(45) NOT NULL,
  `geographicalLocation` VARCHAR(45) NOT NULL,
  `stars` VARCHAR(45) NOT NULL,
  `equipment` VARCHAR(45) NOT NULL,
  `users_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`hotels_id`),
  INDEX `users_id` (`users_id` ASC) VISIBLE,
  CONSTRAINT `users_id_fk`
    FOREIGN KEY (`users_id`)
    REFERENCES `project`.`users` (`users_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `project`.`images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`images` ;

CREATE TABLE IF NOT EXISTS `project`.`images` (
  `images_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `caption` VARCHAR(45) NOT NULL,
  `hotels_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`images_id`),
  INDEX `fk_images_hotels1_idx` (`hotels_id` ASC) VISIBLE,
  CONSTRAINT `fk_images_hotels1`
    FOREIGN KEY (`hotels_id`)
    REFERENCES `project`.`hotels` (`hotels_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
